### ISSUE TITLE
Does not work with JOSM 10392

### ISSUE THREAD

**Issue by Zverik** [Gubaer/josm-contourmerge-plugin#12] opened 2016-06-15 22:03 UTC
I assume it also doesn't work with the current tested JOSM.
I click on nodes and nothing happens. No crosses, no dragging.

**Comment by michaelzangl** [comment] 2016-06-19 17:12
There was a lot of fluctuation in the layer state code the last few days. I tested it using this patch, it should work then ;-)

https://josm.openstreetmap.de/ticket/13001

**Comment by Zverik** [comment] 2016-06-20 14:52
Thanks Michael!

**Comment by Gubaer** [comment] 2016-07-30 21:55
I have built and published a new version of the plugin for the current JOSM-tested (10526). It seems to work in my environment. Does it work in your environment too?

**Comment by codesman** [comment] 2016-08-23 02:38
Looks like newer Java builds have broken this?? It's broken in 10786/1.8.0_101 on OS X 10.11.5, but does work in 10786/1.8.0_72 on OS X 10.11.6.  Was working on OS X 10.11.5 before 10786(not sure which Java) so it doesn't appear to be an OS issue.

Hitting the T(or toolbar icon) activates contourmerge, but then when you click on a node, the orange X does not appear.  If you drag one way to another, then it will merge the entire source way to the entire destination way.  It still works "properly" if you split the source and destination ways into the segments you want to work with but obviously this is a poor workaround for multiple reasons.

BTW, thanks for the awesome plugin! Extremely useful.

**Comment by Gubaer** [comment] 2016-09-02 14:23
I tried to reproduce with JOSM 10929 on Linux Ubuntu, but it worked as expected. Is the problem still there or did it disappear with one of the builds after 10786?

**Comment by codesman** [comment] 2016-09-02 16:33
Yup, it is now working as expected in 10929/1.8.0_101 on OS X 10.11.5.  Yay!

**Comment by Gubaer** [comment] 2016-09-02 18:08
Great! Closing.

**Closed by Gubaer** 2016-09-02 18:08 UTC
Labels: defect
